dist: bionic

install:
  - sudo apt-get update
  - sudo apt-get -y install curl make sassc
  - curl -LO 'https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-linux-amd64.tar.gz'
  - tar xvf pandoc-2.9.2.1-linux-amd64.tar.gz
  - export PATH=$(pwd)/pandoc-2.9.2.1/bin:$PATH

script:
  - make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out/public
  keep_history: true
  on:
    branch: master
